domain_path: C:\Users\demir\Desktop\RnD_EMBED\rdmatx\rdmatxplatform\export\rdmatxplatform\sw\standalone_psu_cortexa53_0
app_src_dir: C:\Xilinx\Vitis\2024.1\data\embeddedsw\lib\sw_apps\hello_world
template: hello_world
