domain_path: C:\Users\tugbe\Desktop\master_sem1\embed\project\IP_ENCAPSULATOR\vitis\ip_encapsulator\export\ip_encapsulator\sw\standalone_ps7_cortexa9_0
app_src_dir: C:\Xilinx\Vitis\2024.1\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
